# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 03:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authentication',
            fields=[
                ('key', models.CharField(max_length=500)),
                ('secret', models.CharField(max_length=500)),
                ('bearer', models.CharField(blank=True, default='', max_length=500)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='auth', serialize=False, to='sites.Site')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_id', models.CharField(max_length=100)),
                ('photo_url', models.URLField()),
                ('expanded_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of', models.DateTimeField(auto_now_add=True)),
                ('query', models.CharField(max_length=500)),
                ('limit', models.PositiveIntegerField(default=15)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('status_id', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TwitterUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followers_count', models.PositiveIntegerField()),
                ('user_id', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('profile_image_url', models.URLField()),
                ('screen_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='status',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', related_query_name='status', to='query.TwitterUser'),
        ),
        migrations.AddField(
            model_name='status',
            name='search',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', related_query_name='status', to='query.Search'),
        ),
        migrations.AddField(
            model_name='photo',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', related_query_name='photo', to='query.Status'),
        ),
    ]
