# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 22:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authentication',
            fields=[
                ('key', models.CharField(max_length=500)),
                ('secret', models.CharField(max_length=500)),
                ('bearer', models.CharField(blank=True, default='', max_length=500)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='auth', serialize=False, to='sites.Site')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('photo_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('photo_url', models.URLField()),
                ('height', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='QueryInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=500)),
                ('limit', models.PositiveIntegerField(default=10)),
                ('max_id', models.BigIntegerField()),
                ('success', models.BooleanField(default=False)),
                ('time_of', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-time_of'],
            },
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=500)),
                ('max_id', models.BigIntegerField()),
                ('min_id', models.BigIntegerField()),
                ('last_accessed', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['query', '-max_id'],
                'verbose_name_plural': 'Searches',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('status_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('text', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['-status_id'],
                'verbose_name_plural': 'Statuses',
            },
        ),
        migrations.CreateModel(
            name='TwitterUser',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('screen_name', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('followers_count', models.PositiveIntegerField()),
                ('profile_image_url', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='status',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', related_query_name='status', to='query.TwitterUser'),
        ),
        migrations.AddField(
            model_name='search',
            name='statuses',
            field=models.ManyToManyField(related_name='searches', related_query_name='search', to='query.Status'),
        ),
        migrations.AddField(
            model_name='queryinstance',
            name='search',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', related_query_name='instance', to='query.Search'),
        ),
        migrations.AddField(
            model_name='photo',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', related_query_name='photo', to='query.Status'),
        ),
    ]
