# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['-status_id']},
        ),
        migrations.RemoveField(
            model_name='status',
            name='id',
        ),
        migrations.RemoveField(
            model_name='status',
            name='search',
        ),
        migrations.RemoveField(
            model_name='twitteruser',
            name='id',
        ),
        migrations.AddField(
            model_name='status',
            name='searches',
            field=models.ManyToManyField(related_name='statuses', related_query_name='status', to='query.Search'),
        ),
        migrations.AlterField(
            model_name='status',
            name='status_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='user_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
