# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 17:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0002_auto_20161018_2344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'ordering': ['-max_id'], 'verbose_name_plural': 'Searches'},
        ),
    ]
