# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0002_auto_20161010_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='searches',
        ),
        migrations.AddField(
            model_name='search',
            name='statuses',
            field=models.ManyToManyField(related_name='searches', related_query_name='search', to='query.Status'),
        ),
    ]
