# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0002_auto_20161017_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='retweets',
            field=models.BooleanField(default=False),
        ),
    ]
