# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0003_auto_20161020_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='status',
        ),
        migrations.AddField(
            model_name='status',
            name='photos',
            field=models.ManyToManyField(related_name='statuses', related_query_name='status', to='query.Photo'),
        ),
    ]
