# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0003_search_retweets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='limit',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
