# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 20:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0004_auto_20161020_1940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='twitteruser',
            options={'ordering': ['screen_name']},
        ),
    ]
