# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0004_auto_20161017_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=500)),
                ('limit', models.PositiveIntegerField(default=100)),
                ('max_id', models.BigIntegerField()),
                ('time_of', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-time_of'],
            },
        ),
        migrations.AlterModelOptions(
            name='search',
            options={'ordering': ['query', '-max_id'], 'verbose_name_plural': 'Searches'},
        ),
        migrations.RemoveField(
            model_name='search',
            name='limit',
        ),
        migrations.RemoveField(
            model_name='search',
            name='retweets',
        ),
        migrations.RemoveField(
            model_name='search',
            name='time_of',
        ),
        migrations.AddField(
            model_name='search',
            name='last_accessed',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='search',
            name='max_id',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='search',
            name='min_id',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='status',
            name='status_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='user_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='queryinstance',
            name='search',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', related_query_name='instance', to='query.Search'),
        ),
    ]
