# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0005_auto_20161018_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queryinstance',
            name='limit',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
