# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 20:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0005_auto_20161020_2034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['photo_id']},
        ),
    ]
