# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0006_auto_20161018_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryinstance',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
