# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 00:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0006_auto_20161020_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='next_search',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prev_searches', related_query_name='prev_search', to='query.Search'),
        ),
    ]
