# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 21:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0007_queryinstance_success'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='expanded_url',
        ),
    ]
